vim.opt.number = true -- Pone los numeros a la izquierda
vim.opt.tabstop = 4 -- Se insertan 4 espacios por un tab
vim.opt.splitright = true -- Forza a todos los splits vertical a ir a la derecha de la ventana actual
vim.opt.splitbelow = true
vim.opt.cursorline = true -- Hace un highlight a la linea actual
vim.opt.clipboard = "unnamedplus" -- Le permite a neovim acceder al clipboard del sistema
vim.opt.cmdheight = 2
vim.opt.fileencoding = "utf-8"
vim.opt.mouse = "a" -- Con esto se puede usar el mouse en nvim
vim.opt.expandtab = true -- Convierte los tabs a espacios
vim.opt.syntax = "ON"
vim.opt.termguicolors = true
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.shiftwidth = 4
vim.opt.scrolloff = 8 -- is one of my fav
vim.opt.sidescrolloff = 8
-- vim.opt.guifont = "monospace:h17"
vim.opt.guifont = "monospace:h9"
vim.cmd "set colorcolumn=100" -- Ponemos una línea vertical en la parte vertical 100
